apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: datanode2
  name: datanode2
spec:
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
  selector:
    io.kompose.service: datanode2
status:
  loadBalancer: {}
